### ISSUE TITLE
Add the ability to test inherited PojoFields.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [oshoukry/openpojo#51]
```
In an Abstract Class one may declare a field with its getter and setter.
When another class extends this class, and define other fields with getters & 
setters its not possible to test those.

Ideally, enhance the Setter & Getter testers to include inherited fields.

Things to pay attention to:
  1. Field Shadowing / Over-riding.
  2. Method over-riding.

```

Original issue reported on code.google.com by `oshou...@gmail.com` on 20 Jan 2015 at 3:13

**Comment by lucasjobs** [comment]
Hello everyone!

Seems that Issue 23 answer isn't more applicable in this question.
I need to test attributes and methods inherited, because superclass is abstract and can't be tested. (like getter, setters, default null values).
com.openpojo.registry.ServiceRegistrar doesn't have a getPojoClassAdaptationService().
This functionality exists on openpojo? How to do that?

**Comment by oshoukry** [comment]
Adding asm library to classpath resolved the issue brought up by Lucas.

**Comment by zygimantus** [comment]
What is asm library?

**Comment by oshoukry** [comment]
@zygimantus Which version of OpenPojo are you using?
The dependency for testing abstract classes depends on ASM library version 5+ see http://asm.ow2.io/
Or just add the following to your maven pom file:
```xml
  <dependency>
    <groupId>org.ow2.asm</groupId>
    <artifactId>asm</artifactId>
    <version>5.2</version>
  </dependency>
```
